#!/bin/sh

project_dn() {
  set +v

  . $(pwd)/security/pretty.sh

  # Bring down containers and volumes.
  docker-compose down --volumes
  [ ! $? -eq 0 ] && echo -e "\033[7;31mThere Was a Problem with Command 1\033[0m" && return 1

  # Prune all images by force.
  docker image prune -f
  [ ! $? -eq 0 ] && echo -e "\033[7;31mThere Was a Problem with Command 2\033[0m" && return 1

  # Stop and remove the encryption container.
  docker stop enc_util && docker rm enc_util
  [ ! $? -eq 0 ] && echo -e "\033[7;31mThere Was a Problem with Command 3\033[0m" && return 1

  # Remove all volumes generated by `project_up.sh`
  docker volume rm persist_pgp persist_tls persist_v111_build
  [ ! $? -eq 0 ] && echo -e "\033[7;31mThere Was a Problem with Command 4\033[0m" && return 1
  
  # Define paths generated from inside `enc_util`.
  local host_pgp_path=$(pwd)/security/private_files/pgp
  local host_tls_path=$(pwd)/security/private_files/tls
  local host_gnupg_path=$(pwd)/security/private_files/.gnupg
  # Define path generated from inside `truth_src`.
  local host_vault_path=$(pwd)/security/private_files/vault

  # Remove generated paths that exist.
  [ -d $host_pgp_path ] && rm -rf $host_pgp_path
  [ ! $? -eq 0 ] && echo -e "\033[7;31mThere Was a Problem with Command 5\033[0m" && return 1

  [ -d $host_tls_path ] && rm -rf $host_tls_path
  [ ! $? -eq 0 ] && echo -e "\033[7;31mThere Was a Problem with Command 6\033[0m" && return 1

  [ -d $host_gnupg_path ] && rm -rf $host_gnupg_path
  [ ! $? -eq 0 ] && echo -e "\033[7;31mThere Was a Problem with Command 7\033[0m" && return 1

  [ -d $host_vault_path ] && rm -rf $host_vault_path
  [ ! $? -eq 0 ] && echo -e "\033[7;31mThere Was a Problem with Command 8\033[0m" && return 1

  pretty "Project is Down"
}

project_dn