version: '3'

services:
  api:
    container_name: api_svc
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    depends_on:
      - redis
      - user
    restart: unless-stopped
    ports:
      - target: 9000
        published: 80
        protocol: tcp
        mode: host
    networks:
      - backend
  mongo:
    container_name: mongo_svc
    build:
      context: ./
      dockerfile: ./mongo/Dockerfile
    restart: unless-stopped
    ports:
      - '27017'
    expose:
      - '27017'
    networks:
      - backend
    volumes:
      # A volume to persist our NoSQL database
      - persist_mongo:/data/db
  redis:
    container_name: redis_svc
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    restart: unless-stopped
    # These settings allow tcp-backlog in
    # ./redis/redis.conf to not be capped.
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
    # This setting is required to disable THP support
    # (for now).
    privileged: true
    ports:
      - '6379'
    expose:
      - '6379'
    networks:
      - backend
    volumes:
      # A volume for persisting our database.
      - persist_redis:/data:rw
  user:
    container_name: user_svc
    build:
      context: ./
      dockerfile: ./services/user/Dockerfile
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    ports:
      - '50051'
    expose:
      - '50051'
    networks:
      - backend
networks:
  # frontend:
  backend:
volumes:
  persist_mongo:
  persist_redis:
