version: '3'

services:
  # Our golang GraphQL server that sends gRPC requests.
  api:
    container_name: api_svc
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    depends_on:
      - redis
      - user
    restart: unless-stopped
    ports:
      - target: 9000
        published: 80
        protocol: tcp
        mode: host
    networks:
      - backend

  # The MongoDB instance that holds our databases.
  mongo:
    container_name: mongo_svc
    environment:
      # NOTE:
      # These variables are for initialization purposes only.
      # Credentials of the root user will be updated and rotated.
      # Passing these variables enforces authentication requirement
      # for all `mongo` shells.
      - MONGO_INITDB_ROOT_USERNAME_FILE=/usr/local/etc/mongodb/mongo-root-username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/usr/local/etc/mongodb/mongo-root-password
      - MONGO_INITDB_DATABASE=admin
    build:
      context: ./
      dockerfile: ./mongo/Dockerfile
    depends_on:
      - truth
    restart: unless-stopped
    ports:
      - '27017'
    expose:
      - '27017'
    networks:
      - backend
    volumes:
      # A volume to persist our NoSQL data store.
      - type: volume
        source: persist_mongo
        target: /data/db
        volume:
          nocopy: true

  # The Redis instance that holds our user IDs (UUID v4).
  redis:
    container_name: redis_svc
    build:
      context: ./
      dockerfile: ./redis/Dockerfile
    depends_on:
      - truth
    restart: unless-stopped
    # These settings allow tcp-backlog in
    # ./redis/redis.conf to not be capped.
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
    # This setting is required to disable THP support
    # (for now).
    privileged: true
    ports:
      - '6379'
    expose:
      - '6379'
    networks:
      - backend
    volumes:
      # A volume for persisting our in-memory data store.
      - type: volume
        source: persist_redis
        target: /data
        volume:
          nocopy: true

  user:
    container_name: user_svc
    build:
      context: ./
      dockerfile: ./services/user/Dockerfile
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - '50051'
    expose:
      - '50051'
    networks:
      - backend

  truth:
    container_name: truth_src
    build:
      context: ./
      dockerfile: ./security/Dockerfile
    restart: always
    ports:
      - '8200'
    expose:
      - '8200'
    networks:
      - backend

networks:
  # frontend:
  backend:
volumes:
  persist_mongo:
  persist_redis:
