#!/bin/sh

project_dn() {
  # Bring down containers and volumes.
  docker-compose down --volumes

  # Prune all images by force.
  docker image prune -f

  # Stop and remove the encryption container.
  docker stop enc_util && docker rm enc_util

  # Remove all volumes generated by `project_up.sh`
  docker volume rm persist_pgp persist_tls persist_v111_build
  
  # Define paths generated from inside `enc_util`.
  local host_pgp_path=$(pwd)/security/private_files/pgp
  local host_tls_path=$(pwd)/security/private_files/tls

  # Remove generated paths that exist.
  [ -d $host_pgp_path ] && rm -rf $host_pgp_path
  [ -d $host_tls_path ] && rm -rf $host_tls_path

  echo -e "\033[7;32m\n                         \n Project Completely Down \n                         \033[0m"
}

project_dn