FROM go:alpine

# Will complete this file once services are complete.

# Many thanks and much credit goes to Nico Vergauwen for this repo:
# - https://github.com/kyriediculous/go-grpc-mongodb
#
# This would have taken a lot longer without that to learn from.