FROM golang:1.16.3-alpine3.13

# Set the working directory to where the code is copied.
# WORKDIR /

# Copy local code over to the image.
# COPY --chown=root:root ./api ./code/
# COPY --chown=root:root ./redis/init/authorization ./code/init/authorization/

# Source the script used to populate env variables.
# RUN ["/bin/sh", "-c", ". /code/init/init.sh"]

# Start the server by default.
# CMD ["go", "run", "/code/server.go"]